import { Roboto } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Button from "./components/Button";

const roboto = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <header className="h-20 flex justify-end px-20  items-center bg-slate-900">
          <nav className="flex gap-8">
            <Link href="/">
              <Button>Home</Button>
            </Link>
            <Link href="/page-1">
              <Button>Page 1</Button>
            </Link>
            <Link href="/page-2">
              <Button>Page 2</Button>
            </Link>
          </nav>
        </header>
        <main>{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
